# Generated by Django 3.0.5 on 2021-01-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='hostel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='hostel_room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
