# Generated by Django 3.0.5 on 2020-07-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('Roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('batch', models.IntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('phone_no1', models.IntegerField()),
                ('phone_no2', models.IntegerField()),
                ('hostel', models.CharField(max_length=50)),
                ('roomno', models.IntegerField()),
            ],
        ),
    ]
