# Generated by Django 3.0.5 on 2020-10-31 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeration',
            old_name='Roll_no',
            new_name='roll_no',
        ),
    ]
