# Generated by Django 3.0.5 on 2020-05-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
