# Generated by Django 3.0.5 on 2020-10-31 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_detail_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
