# Generated by Django 3.0.5 on 2020-11-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='link',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
